image: gradle:jdk24-alpine

stages:
  - build
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script:
    - gradle run

tests:
  stage: test
  script:
    - gradle clean test
  coverage: '/    - Instruction Coverage: ([0-9.]+)%/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: jacoco
        path: build/reports/jacoco/test/jacocoTestReport.xml
